_wandb:
    value:
        cli_version: 0.24.2
        e:
            0jkh0ewc5lh2aeb9cgt518d3bc37uwou:
                args:
                    - --node-ip-address=10.218.151.12
                    - --node-manager-port=45361
                    - --object-store-name=/tmp/ray_jojolee/session_2026-02-13_22-31-53_766978_1892786/sockets/plasma_store
                    - --raylet-name=/tmp/ray_jojolee/session_2026-02-13_22-31-53_766978_1892786/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=41238
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=58432
                    - --gcs-address=10.218.151.12:6379
                    - --session-name=session_2026-02-13_22-31-53_766978_1892786
                    - --temp-dir=/tmp/ray_jojolee
                    - --webui=127.0.0.1:8265
                    - --cluster-id=4933bec231ac7f6ced25ae0c533a092232de6999cda2cee65f962c02
                    - --startup-token=229
                    - --worker-launch-time-ms=1771040178159
                    - --node-id=eae5f67731df567c8736d0e82eba984ea8795bbbf2fcb843dd3f8069
                    - --runtime-env-hash=-1916634659
                    - --enable-resource-isolation=false
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1888556142592"
                        used: "188521603072"
                email: jiosephlee@gmail.com
                executable: /vast/projects/myatskar/design-documents/conda_env/open_rlhf_intern/bin/python3.11
                git:
                    commit: b983b131704cf4c2949cb6eb099b8271cabc1ec9
                    remote: git@github.com:jiosephlee/OpenRLHF-Tools.git
                gpu: NVIDIA B200
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-82efc4f8-3212-fc02-655a-a2fab72452e4
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-d3ef8862-bc24-63ca-a793-87730a61cb00
                host: dgx012
                memory:
                    total: "2164173180928"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.39
                program: /vast/projects/myatskar/design-documents/conda_env/open_rlhf_intern/lib/python3.11/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.11.14
                root: /vast/home/j/jojolee/OpenRLHF-Tools/scripts
                slurm:
                    cluster_name: slurm
                    conf: /cm/shared/apps/slurm/etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000000000000000000000FF00000000000000000000000000FF
                    cpu_bind_list: 0x00000000000000000000000000FF00000000000000000000000000FF
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    distribution: cyclic
                    gpus: "2"
                    gpus_on_node: "2"
                    gtids: "0"
                    job_account: myatskar-design-documents
                    job_cpus_per_node: "16"
                    job_end_time: "1771052615"
                    job_gid: "1082874383"
                    job_group: jojolee
                    job_id: "4493601"
                    job_name: bash
                    job_nodelist: dgx012
                    job_num_nodes: "1"
                    job_partition: dgx-b200
                    job_qos: dgx
                    job_start_time: "1771016615"
                    job_uid: "1082874383"
                    job_user: jojolee
                    jobid: "4493601"
                    launch_node_ipaddr: 165.123.216.43
                    localid: "0"
                    mem_per_node: "262144"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: dgx012
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    pmix_mapping_serv: (vector,(0,1,1))
                    pmixp_abort_agent_port: "45541"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "43283"
                    pty_win_col: "206"
                    pty_win_row: "59"
                    srun_comm_host: 165.123.216.43
                    srun_comm_port: "33359"
                    step_gpus: 0,3
                    step_id: "0"
                    step_launcher_port: "33359"
                    step_nodelist: dgx012
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /vast/home/j/jojolee
                    submit_host: login03
                    task_pid: "2383407"
                    tasks_per_node: "1"
                    topology_addr: dgx012
                    topology_addr_pattern: node
                    tres_per_task: cpu=16
                    umask: "0002"
                startedAt: "2026-02-14T03:36:53.543654Z"
                writerId: 0jkh0ewc5lh2aeb9cgt518d3bc37uwou
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": eval/global_step
              "6":
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": eval/*
              "5": 2
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 2
                - 7
                - 13
                - 16
                - 66
            "4": 3.11.14
            "5": 0.24.2
            "6": 4.57.6
            "10":
                - 20
            "12": 0.24.2
            "13": linux-x86_64
actor_init_on_gpu:
    value: false
actor_learning_rate:
    value: 5e-07
actor_num_gpus_per_node:
    value: 2
actor_num_nodes:
    value: 1
adam_betas:
    value:
        - 0.9
        - 0.95
adam_offload:
    value: false
advantage_estimator:
    value: dr_grpo
agent_func_path:
    value: null
agent_max_steps:
    value: 5
apply_chat_template:
    value: true
async_queue_size:
    value: 1
async_train:
    value: false
attn_implementation:
    value: flash_attention_2
aux_loss_coef:
    value: 0
chat_protocol:
    value: glm_flash
ckpt_path:
    value: ./ckpt/checkpoints_ppo_ray
colocate_actor_ref:
    value: false
colocate_all_models:
    value: true
colocate_critic_reward:
    value: false
critic_learning_rate:
    value: 9e-06
critic_num_gpus_per_node:
    value: 8
critic_num_nodes:
    value: 1
critic_pretrain:
    value: null
deepcompile:
    value: false
deepspeed_enable_sleep:
    value: true
delete_local_after_push:
    value: true
disable_ds_ckpt:
    value: false
disable_fast_tokenizer:
    value: false
ds_tensor_parallel_size:
    value: 1
dual_clip:
    value: null
dynamic_filtering:
    value: true
dynamic_filtering_reward_range:
    value:
        - 0
        - 1
ema_beta:
    value: 0.992
enable_ema:
    value: false
enable_prefix_caching:
    value: true
enable_vllm_is_correction:
    value: true
enforce_eager:
    value: false
entropy_loss_coef:
    value: null
eps_clip:
    value: 0.2
eps_clip_low_high:
    value:
        - 0.2
        - 0.27
eval_dataset:
    value: OpenRLHF/aime-2024
eval_n_samples_per_prompt:
    value: 4
eval_split:
    value: train
eval_steps:
    value: 5
eval_temperature:
    value: 1
freezing_actor_steps:
    value: -1
full_determinism:
    value: false
gamma:
    value: 1
generate_max_len:
    value: 6144
grad_accum_dtype:
    value: null
gradient_checkpointing:
    value: true
gradient_checkpointing_use_reentrant:
    value: false
init_kl_coef:
    value: 0
input_key:
    value: prompt
input_template:
    value: null
is_vlm:
    value: false
kl_estimator:
    value: k1
kl_horizon:
    value: 10000
kl_target:
    value: null
l2:
    value: 0
label_key:
    value: label
lambd:
    value: 1
load_checkpoint:
    value: false
load_in_4bit:
    value: false
local_rank:
    value: -1
logging_steps:
    value: 1
lora_alpha:
    value: 16
lora_dropout:
    value: 0
lora_rank:
    value: 0
lr_scheduler:
    value: cosine_with_min_lr
lr_warmup_ratio:
    value: 0.03
max_ckpt_mem:
    value: 1e+08
max_ckpt_num:
    value: 3
max_epochs:
    value: 1
max_len:
    value: null
max_norm:
    value: 1
max_samples:
    value: 800
micro_rollout_batch_size:
    value: 4
micro_train_batch_size:
    value: 2
n_samples_per_prompt:
    value: 8
no_advantage_std_norm:
    value: false
normalize_reward:
    value: false
num_episodes:
    value: 1
overlap_comm:
    value: false
overlong_buffer_len:
    value: 5120
overlong_penalty_factor:
    value: 0.5
packing_samples:
    value: true
param_dtype:
    value: bf16
perf:
    value: false
policy_loss_type:
    value: ppo
pretrain:
    value: OpenRLHF/Llama-3-8b-sft-mixture
prompt_construction_mode:
    value: manual
prompt_data:
    value: OpenRLHF/dapo-math-17k
prompt_data_probs:
    value: null
prompt_max_len:
    value: 1536
prompt_split:
    value: train
ptx_coef:
    value: 0.05
push_to_hub:
    value: jiosephlee/grpo-baseline-math
push_to_hub_private:
    value: false
ref_num_gpus_per_node:
    value: 2
ref_num_nodes:
    value: 1
ref_reward_offload:
    value: false
remote_rm_url:
    value:
        - /vast/home/j/jojolee/OpenRLHF-Tools/examples/python/math_reward_func.py
reward_clip_range:
    value:
        - -10
        - 10
reward_num_gpus_per_node:
    value: 8
reward_num_nodes:
    value: 1
reward_pretrain:
    value: null
ring_attn_size:
    value: 1
ring_head_stride:
    value: 1
rollout_batch_size:
    value: 16
rollout_max_tokens_per_gpu:
    value: 16192
rollout_trace_dir:
    value: null
save_hf_ckpt:
    value: true
save_path:
    value: /vast/home/j/jojolee/OpenRLHF-Tools/saves/baseline/baseline-grpo-math_2026-02-13_22-31-39
save_steps:
    value: .inf
save_value_network:
    value: false
seed:
    value: 42
stop_properly_penalty_coef:
    value: 0
target_modules:
    value: all-linear
tdc_tools:
    value: null
temperature:
    value: 1
top_p:
    value: 0.95
train_batch_size:
    value: 16
train_max_tokens_per_gpu:
    value: 16192
use_ds_universal_ckpt:
    value: false
use_dynamic_batch:
    value: true
use_kl_loss:
    value: false
use_liger_kernel:
    value: false
use_ms:
    value: false
use_tensorboard:
    value: null
use_wandb:
    value: "1"
value_clip:
    value: 0.5
value_head_prefix:
    value: score
vllm_enable_sleep:
    value: true
vllm_generate_batch_size:
    value: 16
vllm_gpu_memory_utilization:
    value: 0.85
vllm_is_correction_type:
    value: icepop
vllm_is_truncated_threshold:
    value:
        - 0.5
        - 5
vllm_num_engines:
    value: 2
vllm_stop_strings:
    value: null
vllm_sync_backend:
    value: nccl
vllm_sync_with_ray:
    value: false
vllm_tensor_parallel_size:
    value: 1
wandb_group:
    value: null
wandb_org:
    value: null
wandb_project:
    value: openrlhf_baseline
wandb_run_name:
    value: baseline-grpo-math_2026-02-13_22-31-39
zero_stage:
    value: 1
zpg:
    value: 1
